### ISSUE TITLE
Windows环境下，在执行flask run时报错

### ISSUE THREAD

**Issue by HYJJJJJJJJ** [greyli/watchlist#12]
## 环境：

- Windows 10
- Python 3.9
- （自行升级的Werkzeug 0.15.5）

## 报错：

在成功执行了flask initdb/admin/forge之后，执行flask run，报错如下：

`d:\pycharmprojects\web-server-for-embedded-competition\venv\scripts\python.exe: No module named D:\PyCharmProjects\web-server-for-embedded-competition\venv\Scripts\flask`

看着像是一个很简单的问题，执行命令的时候没有给flask加上.exe的后缀，但是不知道具体怎么解决呢？

**Comment by HYJJJJJJJJ** [comment]
在虚拟机中使用Ubuntu18验证了一遍，可以正常运行~但是还是想知道win环境下如何解决呢？

**Comment by greyli** [comment]
看起来和环境相关，可以考虑重新创建虚拟环境试试。后续还有问题可以发到 [HelloFlask 论坛](https://discuss.helloflask.com)，谢谢。
