### ISSUE TITLE
Pythonanywhere OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by dzzzzz123** [greyli/watchlist#13]
报错了
![image](https://user-images.githubusercontent.com/65523902/134469020-e714e1cb-08f9-41d5-9688-0537ad200f21.png)
![image](https://user-images.githubusercontent.com/65523902/134469045-b1022ee5-02eb-4825-af36-d4c03a1d3afd.png)

**Comment by greyli** [comment]
可以用 lsof 命令看一下端口被哪个程序占用：

```
lsof -i :5000
```

然后 kill 掉输出的进程 id：

```
kill 1234
```
