### ISSUE TITLE
Flask入门教程第四章 静态文件 提问

### ISSUE THREAD

**Issue by SharplessSword** [greyli/watchlist#15]
![image](https://user-images.githubusercontent.com/102005920/160595119-c5f81cd5-9356-4689-8fa0-56823a10b5c2.png)
添加图片中的filename命名是否应该如变量名名字 仅包含文件名，目录部分'/iamges/.'放到static后面，
```
<h2>
<img alt="Avatar" src="{{ url_for('static/images
/', filename='avatar.png') }}">
{{ name }}'s Watchlist
</h2>
...
<img alt="Walking Totoro" src="{{ url_for('static/images
/', filename='totoro.gif') }}">
```

**Comment by greyli** [comment]
`static` 可以理解成是一个内置的视图函数的名字（端点值），不能随意改变。`filename` 参数是 `static` 文件夹目录下的相对路径。
