### ISSUE TITLE
不知道为什么无法解析文件

### ISSUE THREAD

**Issue by Leesennenjoyu** [greyli/watchlist#8]
<img width="1469" alt="iShot2021-04-28 17 18 52" src="https://user-images.githubusercontent.com/58732522/116379730-e437bd00-a845-11eb-97ae-4ac2dd83b6a3.png">

**Comment by greyli** [comment]
问题不是这样问的……你需要提供尽可能多的相关信息才行，而不是扔出来一句话一张图然后让别人去猜测你遇到了什么问题。另外，这里只用来反馈 watchlist 项目本身的 bug，对于你自己的代码问题，请发到 [HelloFlask 论坛](https://discuss.helloflask.com)，烦请使用纯文本的形式提供代码，并给出「无法解析文件」的具体表现。
